name: build-and-push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml)
          VERSION="v$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=VERSION::$VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            athomas22/wal-g-pruner:latest
            athomas22/wal-g-pruner:${{ steps.get_version.outputs.VERSION }}

      - name: Get Previous Tag
        id: get_previous_tag
        run: |
          PREV_TAG=$(git describe --abbrev=0 --tags)
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV
          echo "::set-output name=PREV_TAG::$PREV_TAG"
    
      - name: Generate Changelog
        id: generate_changelog
        uses: nblagoev/pull-release-notes-action@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          base-ref: ${{ steps.get_previous_tag.outputs.PREV_TAG }}
          head-ref: ${{ github.sha }}

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.get_version.outputs.VERSION }}',
              sha: context.sha
            })
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.generate_changelog.outputs.result }}
          draft: true

      
