name: changelog-and-release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml)
          VERSION="v$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=VERSION::$VERSION"
  
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          draft: true
